spring.application.name=server
spring.datasource.url=jdbc:postgresql://localhost:5432/assignmentreaderusers
spring.datasource.username=phuctran
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update